# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: README Update

on:
  push:
    branches: [ "master" ]
    paths: ['dialogues/**.csv']
  pull_request:
    branches: [ "master" ]
    paths: ['dialogues/**.csv']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update translated progress 
      run: |
        python progress.py
        python progress.py docs/README-TH.md
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: '📝 docs: 🤖 auto update translated progress'
